# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  database:
    env_file:
      - .env
    container_name: dbmaster
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"

  # App Service
  app:
    build: .
    image: todo_app
    restart: always
    container_name: todo
    env_file:
      - .env
    ports:
      - "3030:3030"
    depends_on:
      - database
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - default
  
  
  